services:
  app:
    build: .
    container_name: websocketww
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest # Imagem mais recente do MongoDB
    container_name: websocket-chat-mongo
    ports:
      - "27017:27017"  # Expondo a porta 27017 para acessar o MongoDB
    